#!/usr/bin/env bash
# displays a list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Show process hierachy
# Display in a user oriented format

ps -auxf
